apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fiap-todo-prod

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: production

images:
- name: fiap-todo-api
  newName: 712819938659.dkr.ecr.us-east-1.amazonaws.com/cicd
  newTag: 7eb4a018b6d0b61c710168066d3bd148aee8dfe5
